### PR TITLE
[TL] test flashattention script

### PR DESCRIPTION
**Pull request by tzj-fxz**
[TL] test flashattention script

### CODE REVIEW

**Comment by LeiWang1999** [comment]
@tzj-fxz code under the main body that be commented should be removed.

**Comment by LeiWang1999** [comment]
@tzj-fxz Please run `format.sh` to resolve the linting issues.

**Comment by tzj-fxz** [comment]
@LeiWang1999 Thanks, the second commit fix the format issue

**Comment by LeiWang1999** [comment]
LGTM

**Pull request merged**
